#!/usr/bin/env -S bash -euET -o pipefail -O inherit_errexit

if [[ -n ${TAG-} ]]; then
    echo ${TAG} > parse_changelog/VERSION
    cat parse_changelog/VERSION
    exit 0
fi

# Make sure we have the latest tags
git fetch --tags --force --prune --prune-tags

current_tag=$(git tag --list 'v*' | tr -d 'v' | sort -Vur | head -n1)
[[ -z ${current_tag} ]] && current_tag="0.0.0"

echo ${current_tag} > parse_changelog/VERSION
cat parse_changelog/VERSION
